In [ ]:
# numpy array merging --------------------


🎯 Summary:

vstack() — rows add karne ke liye (upar neeche)
hstack() — columns add karne ke liye (aage peeche)
concatenate() — rows ya columns dono add kar sakte ho (flexible)
vsplit() — rows ke hisaab se todna
hsplit() — columns ke hisaab se todna

# vertical merging

In [44]:
# 1. numpy.vstack() (Vertical Stacking)
# Is function se arrays upar neeche (row-wise) stack hote hain, matlab vertically chipak jaate hain!
# Dono arrays ka shape same hona chahiye, sirf pehli axis (rows) pe difference ho sakta hai.
import numpy as np
arr1=np.array([3,4,56,12,5])
arr2=np.array([6,7,8,89,10])
result=np.vstack((arr1,arr2))
print(result)

[[ 3  4 56 12  5]
 [ 6  7  8 89 10]]


# horizontal merging

In [47]:
import numpy as np
arr1=np.array([3,4,56,12,5])
arr2=np.array([6,7,8,89,10])
result=np.hstack((arr1,arr2))
print(result)

[ 3  4 56 12  5  6  7  8 89 10]


# concatenate

In [50]:
import numpy as np
arr1=np.array([3,4,56,12,5])
arr2=np.array([6,7,8,89,10])
result=np.concatenate((arr1,arr2))
print(result)

[ 3  4 56 12  5  6  7  8 89 10]


In [51]:
# splitting of numpy array------

# vertical splitting

In [53]:
import numpy as np
arr = np.arange(9.0).reshape(3, 3)
out_arr = np.vsplit(arr, 1)
print(out_arr)


[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


# horizontal splitting

In [55]:
import numpy as np
arr = np.arange(9.0).reshape(3, 3)
out_arr = np.hsplit(arr,1)
print(out_arr)

[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]
