In [4]:
# sorting in numpy array:------
import numpy as np
arr = np.array([[7, 3, 8, 6, 4], [7, 2, 9, 8, 6], [5, 4, 2, 3, 1]])
print(np.sort(arr))

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]


In [18]:
# to sort the array according to the sorting method
print("quicksort:",np.sort(arr,kind='quicksort'))
print("mergesort:",np.sort(arr,kind='mergesort'))
print("heapsort:",np.sort(arr , kind = 'heapsort'))

quicksort: [[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]
mergesort: [[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]
heapsort: [[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]
